#!/bin/bash
#SBATCH --job-name="omp-cpu-shared"
#SBATCH --output="omp4096.%J.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=32G
#SBATCH --export=ALL
#SBATCH --account=csd453
#SBATCH -t 01:00:00

# AOCC environment
module purge
module load slurm
module load cpu
module load aocc

#SET the number of openmp threads
export OMP_NUM_THREADS=1

#Run the openmp job
./omp_1024_c
